import type { Metadata } from "next";
import "../styles/globals.css";
import AdminLayout from "@/components/Layout/admin-layout";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <Providers>
          <AdminLayout>{children}</AdminLayout>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
